#!/usr/bin/env python3
"""Splice EEE 202 (Applied Electricity II) into data.js: course, topics,
questions, plus StudyRunner deep dives (written-exam formula sheets)."""
import json

DATA = json.load(open(".eee202_out.json"))
TOPICS = DATA["topics"]
QUESTIONS = DATA["questions"]

COURSE = {
    "id": "eee202",
    "code": "EEE 202",
    "title": "Applied Electricity II",
    "blurb": "Magnetism, AC waveforms & phasors, resonance, AC network theorems, magnetic circuits & transformers, motors & generators, instrumentation and nonlinear circuits. Built for a WRITTEN exam: 67 fully worked calculation questions (Given → Formula → Substitute → Answer, exactly as you must write them) plus high-yield theory questions with one-line answers you can memorise tonight.",
    "accent": "#7c3aed",
    "available": True,
}

DEEP_DIVES = [
("eee-magnetism",
"""MAGNETISM & MOVING CHARGES — Written-exam formula sheet:
FORCE ON A MOVING CHARGE: F = q × v × B × sin θ (θ = angle between v and B). If the charge moves PARALLEL to the field, θ = 0 → F = 0. Units: F (N), q (C), v (m/s), B (T).
FORCE ON A CURRENT-CARRYING CONDUCTOR: F = B × I × l × sin θ.
SOLENOID FIELD: B = μ₀ × n × I with n = N/L (turns per metre); μ₀ = 4π × 10⁻⁷ T·m/A.
FARADAY'S LAWS: 1st — changing flux through a conductor induces an e.m.f. (current flows if the circuit is closed). 2nd — E = N × (dΦ/dt); use E = N × (ΔΦ/Δt) for uniform changes. Lenz's law gives direction (minus sign).
MOTIONAL EMF: E = B × l × v (conductor cutting flux at right angles).
KEY DEFINITIONS: e.m.f. = that which tends to produce current (unit volt). Magnetism = force produced by moving charges. Like poles repel; unlike attract. Magnetite (Fe₃O₄) = first known magnet. B-field (tesla) = field defined by force on a moving charge; H-field (A/m) = field within a material. 1 T = 10⁴ gauss. Field lines: never cross, closed loops, parallel lines repel.
EXAM WRITING STYLE (copy this): 1) Write the formula. 2) Substitute the numbers WITH units. 3) Box the answer with its unit. Example: "F = q × v × B × sinθ = 4 × 20 × 10 × sin30° = 400 N."""),
("eee-ac-phasors",
"""AC WAVEFORMS & PHASORS — Written-exam formula sheet:
SINUSOID: A(t) = Aₘ sin(2πft). DC = uni-directional, constant; AC = bi-directional, time-varying.
PERIOD & FREQUENCY: f = 1/T (Hz); T in seconds. ω = 2πf (rad/s).
PEAK / RMS / AVERAGE: Vᵣₘₛ = Vₘ/√2 = 0.707 × Vₘ; Vₘ = 1.414 × Vᵣₘₛ; Vₐᵥₑ (half cycle) = 0.637 × Vₘ.
REACTANCE: Xₗ = 2πfL (Ω); XC = 1/(2πfC) (Ω). Xₗ rises with frequency; XC falls with frequency.
IMPEDANCE: Z = R + jXₗ (inductive) or Z = R − jXC (capacitive); magnitude |Z| = √(R² + X²).
PHASOR: a rotating vector (magnitude = peak/rms value, angle = phase). Steinmetz (GE, 1893) introduced the symbolic method. Phasors add like vectors — use them to add sinusoids without trigonometry.
KEY THEORY: AC cannot be stored in batteries; it is generated by alternators. The waveform above the zero line = one direction, below = the opposite direction.
EXAM WRITING STYLE: always state whether your answer is rms or peak — examiners penalise mixed-up values."""),
("eee-resonance",
"""RESONANCE IN AC CIRCUITS — Written-exam formula sheet:
SERIES RESONANCE: condition Xₗ = XC. Impedance is MINIMUM (Z = R), current is MAXIMUM, power factor = 1.
RESONANT FREQUENCY: f₀ = 1/(2π√(LC)). Derivation: 2πfL = 1/(2πfC) → solve for f.
Q FACTOR (quality/selectivity): Q = Xₗ/R = XC/R at resonance. Bandwidth = f₀/Q.
PARALLEL RESONANCE (anti-resonance): impedance is MAXIMUM (the L and C currents cancel) — the combination acts like an open circuit.
KEY THEORY: high Q → sharp, selective resonance with narrow bandwidth. At resonance the circuit is purely resistive, so voltage and current are in phase.
EXAM WRITING STYLE: for f₀ problems, first compute LC, then √(LC), then 1/(2π√(LC)) — show all three lines for full marks."""),
("eee-network-theorems",
"""NETWORK THEOREMS FOR AC — Written-exam formula sheet:
THÉVENIN: any linear two-terminal network = voltage source Vₜₕ (open-circuit voltage) in SERIES with Zₜₕ (impedance seen with sources killed). For AC, Zₜₕ is complex (R ± jX).
NORTON: dual — current source Iₙ (short-circuit current) in PARALLEL with Zₙ = Zₜₕ.
SUPERPOSITION: in a linear network, the response = algebraic sum of responses from each source acting alone (voltage sources shorted, current sources opened). Works for AC with phasors.
SERIES/PARALLEL IMPEDANCES: series adds: Z = Z₁ + Z₂; two equal impedances in parallel give Z/2; Zₑ = Z₁ × Z₂ / (Z₁ + Z₂) in general. |Z| = √(R² + X²).
NONLINEAR CIRCUITS: linear ⇔ i-v graph is a straight line; y = x² and y = |x| (piecewise linear) are nonlinear. Key nonlinear op-amp circuit: the negative resistance converter → used to build oscillators.
EXAM WRITING STYLE: for AC theorems, keep the j's through every line — dropping them loses phase information and marks."""),
("eee-magcircuits-transformer",
"""MAGNETIC CIRCUITS & TRANSFORMERS — Written-exam formula sheet:
MAGNETIC CIRCUIT (Ohm's-law analogy): m.m.f. F = NI (At); field strength H = F/L = NI/L (A/m); flux density B = μH (T); flux Φ = B × A (Wb); reluctance S = l/(μA) (A/Wb); magnetic Ohm's law: Φ = F/S.
PERMEABILITY: μ₀ = 4π × 10⁻⁷ H/m (free space); relative μᵣ = μ/μ₀ (dimensionless); absolute μ = μ₀μᵣ.
ELECTROSTATICS ↔ ELECTROMAGNETISM: flux↔flux, D↔B, E↔H, e.m.f.↔m.m.f., p.d.↔magnetic p.d., ε↔μ, ε₀↔μ₀.
TRANSFORMER (ideal): V₁/V₂ = N₁/N₂ = I₂/I₁. Step-up: N₂ > N₁ (V rises, I falls); step-down: N₂ < N₁. Power: V₁ × I₁ = V₂ × I₂.
LOSSES: copper (I²R in windings) + iron (eddy current + hysteresis). Transformers work ONLY on AC — induction needs changing flux (E = N dΦ/dt).
EXAM WRITING STYLE: for transformer questions write the ratio equation first, then rearrange — never guess the direction of the ratio."""),
("eee-motors-generators",
"""MOTORS & GENERATORS — Written-exam formula sheet:
ENERGY CONVERSION: motor = electrical → mechanical; generator = mechanical → electrical. Both are coupled through the magnetic field (Faraday, 1831: motion in a field → e.m.f.; current in a field → force).
MOTIONAL EMF: E = B × l × v (v ⊥ B and l).
RULES: Fleming's LEFT-hand rule = MOTOR (force on a current-carrying conductor); RIGHT-hand rule = GENERATOR (direction of induced e.m.f.).
DC MACHINE PARTS: armature (rotating windings where e.m.f. is generated), field system (produces flux), commutator (rectifies the armature's AC into DC output), brushes.
KEY THEORY: battery = stored chemical energy source; generator = e.m.f. from motion in a field. An AC generator is called an alternator.
EXAM WRITING STYLE: state the energy conversion direction first ("the machine converts X into Y"), then apply E = B × l × v with units."""),
("eee-instruments",
"""INSTRUMENTS & INSTRUMENTATION — Written-exam formula sheet:
DEFINITION: instrumentation = using devices to detect, observe, measure, control, compute, communicate and display physical quantities. Instruments extend human senses — accurate, rapid measurement over great ranges.
CONNECTIONS: ammeter = in SERIES, very LOW resistance (must not disturb the current); voltmeter = in PARALLEL, very HIGH resistance (must draw negligible current).
MOVEMENTS: PMMC (moving coil) = DC only, uniform scale, polarity matters; moving iron = AC and DC (r.m.s.), robust but non-uniform scale.
EXTENDING RANGES: voltmeter — total resistance Rₜ = V / (full-scale deflection current), multiplier = Rₜ − Rₘ; ammeter — shunt Rₛₕ = (Iₘ × Rₘ) / (I − Iₘ).
CLASSIFICATION: analog (pointer/scale) vs digital (numeric display). Errors: friction in the movement; parallax when reading the pointer (use mirror scales).
EXAM WRITING STYLE: for multiplier/shunt problems write the two currents (movement vs diverted) clearly before applying the formulas."""),
("eee-nonlinear",
"""NONLINEAR CIRCUITS (INTRO) — Written-exam formula sheet:
LINEAR vs NONLINEAR: a circuit is linear if its i-v graph is a straight line (v = Ri); any other shape = nonlinear. y = x² (parabola) is nonlinear; y = |x| is piecewise linear but still nonlinear because it cannot be written as y = ax + b.
WHY IT MATTERS: amplifiers, computers and most real devices are built from nonlinear components — nonlinear analysis is 'the real engineering' (no hard-and-fast rules; systematic methods exist for op-amp nonlinear circuits).
KEY CIRCUIT: the negative resistance converter — an op-amp circuit whose i-v slope is negative over a region; it supplies power instead of absorbing it, which makes it the core of an OSCILLATOR.
EXAM WRITING STYLE: always justify 'nonlinear' by referring to the shape of the i-v graph, not by listing components."""),
]

def find_bracket_end(s, start):
    depth = 0
    i = start
    in_str = False
    esc = False
    while i < len(s):
        c = s[i]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
        else:
            if c == '"':
                in_str = True
            elif c == "[":
                depth += 1
            elif c == "]":
                depth -= 1
                if depth == 0:
                    return i + 1
        i += 1
    raise ValueError("unbalanced brackets")

def fmt_questions(qs):
    out = []
    for q in qs:
        lines = ["  {"]
        entries = []
        for key in ["id", "topicId", "kind", "question", "options", "correct", "short", "solution", "image"]:
            if key not in q:
                continue
            val = q[key]
            if key == "options":
                entries.append(f'    "{key}": [\n' + ",\n".join(f'      "{o}"' for o in val) + "\n    ]")
            elif key == "correct":
                entries.append(f'    "{key}": {val}')
            else:
                entries.append(f'    "{key}": {json.dumps(val, ensure_ascii=False)}')
        lines.append(",\n".join(entries))
        lines.append("  }")
        out.append("\n".join(lines))
    return ",\n".join(out)

def fmt_topics(topics):
    out = []
    for t in topics:
        lines = ["    {"]
        entries = [f'      "id": "{t["id"]}"', f'      "name": "{t["name"]}"']
        lines.append(",\n".join(entries))
        lines.append("    }")
        out.append("\n".join(lines))
    return ",\n".join(out)

def main():
    src = open("src/data.js").read()

    # ---- 1) insert course before mee206 ----
    i_mee = src.find('"mee206"')
    if i_mee < 0:
        raise SystemExit("mee206 not found")
    # find the object start (the last '{' line before it)
    obj_start = src.rfind("{", 0, i_mee)
    course_block = json.dumps(COURSE, ensure_ascii=False, indent=2).replace('"available": true', '"available": true')
    # make it look like the existing style (4-space indent, trailing comma)
    course_lines = ["  {"]
    entries = [
        f'    "id": "{COURSE["id"]}"',
        f'    "code": "{COURSE["code"]}"',
        f'    "title": "{COURSE["title"]}"',
        f'    "blurb": {json.dumps(COURSE["blurb"], ensure_ascii=False)}',
        f'    "accent": "{COURSE["accent"]}"',
        '    "available": true',
    ]
    course_lines.append(",\n".join(entries))
    course_lines.append("  },")
    block = "\n".join(course_lines) + "\n"
    src = src[:obj_start] + block + src[obj_start:]

    # ---- 2) add topics under a new key eee202 in topicMeta ----
    i_tm = src.find("export const topicMeta = {")
    i_close = src.find("\n}", i_tm)
    if i_close < 0:
        raise SystemExit("topicMeta close not found")
    topic_block = (
        ',\n  "eee202": [\n'
        + fmt_topics(TOPICS)
        + "\n  ]\n"
    )
    src = src[:i_close] + topic_block + src[i_close:]

    # ---- 3) add questionBank.eee202 ----
    i_qb = src.find("export const questionBank = {")
    i_close2 = src.find("\n}", i_qb)
    if i_close2 < 0:
        raise SystemExit("questionBank close not found")
    q_block = (
        ',\n  eee202: [\n'
        + fmt_questions(QUESTIONS)
        + "\n  ]\n"
    )
    src = src[:i_close2] + q_block + src[i_close2:]

    open("src/data.js", "w").write(src)
    print(f"data.js: course + {len(TOPICS)} topics + {len(QUESTIONS)} questions")

    # ---- 4) StudyRunner deep dives ----
    sr = open("src/components/StudyRunner.jsx").read()
    marker = "const TOPIC_DEEP_DIVE = {"
    i_dd = sr.find(marker)
    i_imgs = sr.find("const TOPIC_IMAGES", i_dd)
    close = sr.rfind("\n}", i_dd, i_imgs)
    if close < 0:
        raise SystemExit("deep dive close not found")
    entries = [f"  '{key}': `{text}`" for key, text in DEEP_DIVES]
    insertion = ",\n".join(entries) + ",\n"
    sr = sr[:close] + insertion + sr[close:]
    open("src/components/StudyRunner.jsx", "w").write(sr)
    print(f"StudyRunner: +{len(DEEP_DIVES)} deep dives")

if __name__ == "__main__":
    main()
